import esbuild from "esbuild";
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { builtinModules, createRequire } from "node:module";

const require = createRequire(import.meta.url);
const prod = process.argv[2] === "production";

// main.js is the only file that reaches a user and the ThorVG binary inside it
// carries no readable notices, so a short legal header names what is bundled
// and points at the full texts. `/*!` marks it as a legal comment for tooling.
const webcanvasVersion = JSON.parse(
  await fs.readFile(path.join(path.dirname(require.resolve("@thorvg/webcanvas")), "..", "package.json"), "utf8"),
).version;

const banner = `/*!
 * Lottie — Obsidian plugin. MIT License; see LICENSE.
 * Bundles ThorVG WebCanvas ${webcanvasVersion} (MIT) as WebAssembly, which statically
 * links RapidJSON (MIT), JerryScript (Apache-2.0) and libwebp (BSD-3-Clause).
 * Full notices: THIRD-PARTY-LICENSES.md in the source repository.
 *
 * Generated by esbuild; the source lives in the plugin's repository.
 */
`;

// Obsidian's community installer only downloads main.js, manifest.json and
// styles.css from a release, so thorvg.wasm can never arrive as its own file.
// It is embedded in the bundle instead: esbuild's `binary` loader base64s the
// bytes at build time and decodes them to a Uint8Array at runtime.
const wasmFile = path.join(path.dirname(require.resolve("@thorvg/webcanvas")), "thorvg.wasm");

const wasmPlugin = {
  name: "thorvg-wasm",
  setup(build) {
    build.onResolve({ filter: /^thorvg-wasm$/ }, () => ({
      path: wasmFile,
      namespace: "wasm-binary",
    }));
    build.onLoad({ filter: /.*/, namespace: "wasm-binary" }, async (args) => ({
      contents: await fs.readFile(args.path),
      loader: "binary",
    }));
  },
};

await esbuild.build({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", ...builtinModules],
  format: "cjs",
  target: "es2022",
  platform: "browser",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  plugins: [wasmPlugin],
});
